# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  KONAN_USER_HOME: '/home/vsts/.konan'

steps:
- task: Cache@2.198.0
  inputs:
    key: 'gradle | "$(Agent.OS)"'
    restoreKeys: gradle
    path: $(GRADLE_USER_HOME)
  displayName: Gradle Build Cache

- task: Cache@2.198.0
  inputs:
    key: 'konan | "$(Agent.OS)"'
    restoreKeys: konan
    path: $(KONAN_USER_HOME)
  displayName: Konan Build Cache

- task: Gradle@2.208.0
  displayName: 'Gradle Build : Kotlin Native'

- script: './gradlew --stop'    
  displayName: Stop Gradle Daemon
