# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  ${{ if eq( variables['Agent.OS'], 'Windows_NT' ) }}:
    KONAN_USER_HOME: 'C:/Users/VssAdministrator/.konan'
  ${{ if eq( variables['Agent.OS'], 'Linux' ) }}:
    KONAN_USER_HOME: '/home/vsts/.konan'
  ${{ if eq( variables['Agent.OS'], 'Darwin' ) }}:
    KONAN_USER_HOME: '/Users/runner/.konan'

steps:
- task: Cache@2
  inputs:
    key: 'gradle | "$(Agent.OS)"'
    restoreKeys: gradle
    path: $(GRADLE_USER_HOME)
  displayName: Gradle Build Cache

- task: Cache@2
  inputs:
    key: 'konan | "$(Agent.OS)"'
    restoreKeys: konan
    path: ${{variables.KONAN_USER_HOME}}
  displayName: Konan Build Cache

- task: Gradle@2
  displayName: 'Gradle Build : Kotlin JVM'
  inputs:
    gradleOptions: '-Xmx3072m'

- task: Gradle@2
  displayName: 'Gradle Build : Kotlin Native'
  inputs:
    options: '--build-file app/build-kotlin-native.gradle.kts'
    gradleOptions: '-Xmx3072m'

- script: 'gradlew --stop'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: Stop Gradle Daemon On Windows

- bash: './gradlew --stop'
  condition: ne( variables['Agent.OS'], 'Windows_NT' )
  displayName: Stop Gradle Daemon On Unix